spring:
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false
  application:
    name: CV-back
  datasource:
    url: jdbc:postgresql://localhost:5432/cv
    username: postgres
    password: root
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


server:
  port: 3300
